### ISSUE TITLE
Wrong line in Dokuwiki page

### ISSUE THREAD

**Issue by Chris2000SP** [nginxinc/nginx-wiki#270]
https://github.com/nginxinc/nginx-wiki/blame/master/source/start/topics/recipes/dokuwiki.rst#L34

That make all .php in /lib/ not executable.

**Comment by LinuxJedi** [comment]
Yes, as far as I can tell that is the intention since this contains an SEO recipe to indirectly access the /lib/ PHP scripts. I believe the /lib/ directory is not intended to be directly executable but still may be needed for asset access (hence the expires).

I am not a developer of Dokuwiki and did not write this entry (just ported it from the old wiki) so please let me know if my assertions above are incorrect.

**Comment by Chris2000SP** [comment]
In this line: https://github.com/nginxinc/nginx-wiki/blame/master/source/start/topics/recipes/dokuwiki.rst#L182

It is the right way so please correct that.

**Comment by LinuxJedi** [comment]
that does look like a better way of implementing the intention. Please feel free to submit a pull request with the change in it.

**Comment by LinuxJedi** [comment]
Fixed with merge of #271
