### ISSUE TITLE
clearer error message for nginx -t

### ISSUE THREAD

**Issue by CarstenSchelp** [nginxinc/nginx-wiki#593]
Hi,
When testing my nginx.conf with "nginx -t" on CentOS7 I got the feedback that I'd have to set the value of "server_names_hash_bucket_size" to 64.

1. There was a misleading colon in that recommendation "server_names_hash_bucket_size: 64;" which does not help when the actual required line would be "server_names_hash_bucket_size 64;". (Without colon after the setting name.)
2. The real issue was that the value of 64 is apparently hardcoded. Once I had added the line with "64", "nginx -t" kept saying that I'd have to set the value to 64. This made me investigate if I had edited the wrong file or in a wrong way in a wrong place ... When ultimately just setting the value to 128 _did_ work.

It wouldbe clearer to tell the user:
'Add or change the setting "server_names_hash_bucket_size" in the http section to 64 or a higher base-two value (128, 256, ...)'

Kind regards, Carsten

**Comment by CarstenSchelp** [comment]
Hi Alessandro,The error message that I suggest to improve is not in the Wiki repo, of course. For which repo would I have to create a PR?Kind regards, CarstenSent using the GMX mail appOn 16/05/2022 at 16:09, Alessandro Fael Garcia wrote:
                
            
            
                
                    From: "Alessandro Fael Garcia" ***@***.***>Date: 16 May 2022To: "nginxinc/nginx-wiki" ***@***.***>Cc: "Carsten Schelp" ***@***.***>,"Mention" ***@***.***>Subject: Re: [nginxinc/nginx-wiki] clearer error message for nginx -t (Issue #593)
                
                

Hey @CarstenSchelp! This wiki is 100% community maintained so I would suggest opening up a PR with your suggestions! 😄

**Comment by alessfg** [comment]
Ah I see what you mean. Sorry about that, I originally misread your original issue. Since this seems to be a suggestion for the NGINX package, I would suggest emailing via our mailing list https://mailman.nginx.org/mailman3/lists/. I would caution to first make sure that you are using an NGINX provided package, and not the package provided by CentOS. This is the first time I encounter anyone reporting this issue so if I were a betting man I would bet it's an issue from the CentOS package (in such a case, there is nothing we can do on our end sadly). (A simple way to check if it's one or the other is if you followed the instructions here https://nginx.org/en/linux_packages.html#RHEL-CentOS.)
